export const ALERT_ADD = 'ALERT_ADD'
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD'

export const ALERT_REMOVE = 'ALERT_REMOVE'
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE'

export const SHOW_STRATEGY_ADD_DIALOG = 'SHOW_STRATEGY_ADD_DIALOG'
export const HIDE_STRATEGY_ADD_DIALOG = 'HIDE_STRATEGY_ADD_DIALOG'

export const REFRESH_STRATEGIES_TABLE = 'REFRESH_STRATEGIES_TABLE'